var searchData = [
  [
    "send_0",
    [
      "Send",
      [
        "../classcelte_1_1nl_1_1_kafka_pool.html#ac1a1efbd4252a8bb1678cc13b546ccce",
        1,
        "celte::nl::KPool::Send(kafka::clients::producer::ProducerRecord &amp;record, const std::function&lt; void(const kafka::clients::producer::RecordMetadata &amp;, kafka::Error)&gt; &amp;onDelivered)",
      ],
      [
        "../classcelte_1_1nl_1_1_kafka_pool.html#a189de3d5509d253e107e189f5470d3c0",
        1,
        "celte::nl::KPool::Send(const SendOptions &amp;options)",
      ],
    ],
  ],
  [
    "sendoptions_1",
    [
      "SendOptions",
      [
        "../structcelte_1_1nl_1_1_kafka_pool_1_1_send_options.html",
        1,
        "celte::nl::KPool",
      ],
    ],
  ],
  [
    "set_5finitial_5fstate_2",
    [
      "set_initial_state",
      [
        "../classtinyfsm_1_1_fsm.html#a7423ff0f575dc719589dd42d6aac9670",
        1,
        "tinyfsm::Fsm",
      ],
    ],
  ],
  [
    "start_3",
    [
      "Start",
      [
        "../classcelte_1_1runtime_1_1_celte_runtime.html#ab7874c2f155b841e83c40d26ddf3a6c8",
        1,
        "celte::runtime::CelteRuntime",
      ],
    ],
  ],
  [
    "statelist_4",
    ["StateList", ["../structtinyfsm_1_1_state_list.html", 1, "tinyfsm"]],
  ],
  [
    "statelist_3c_20s_2c_20ss_2e_2e_2e_20_3e_5",
    [
      "StateList&lt; S, SS... &gt;",
      [
        "../structtinyfsm_1_1_state_list_3_01_s_00_01_s_s_8_8_8_01_4.html",
        1,
        "tinyfsm",
      ],
    ],
  ],
  [
    "statelist_3c_3e_6",
    [
      "StateList&lt;&gt;",
      ["../structtinyfsm_1_1_state_list_3_4.html", 1, "tinyfsm"],
    ],
  ],
  [
    "subscribe_7",
    [
      "Subscribe",
      [
        "../classcelte_1_1nl_1_1_kafka_pool.html#a390a7a5adcfed3af7ff5da6bd0bf86ce",
        1,
        "celte::nl::KPool",
      ],
    ],
  ],
  [
    "subscribeoptions_8",
    [
      "SubscribeOptions",
      [
        "../structcelte_1_1nl_1_1_kafka_pool_1_1_subscribe_options.html",
        1,
        "celte::nl::KPool",
      ],
    ],
  ],
];
